### ISSUE TITLE
Error with theme "Theme.MaterialComponents.Light.NoActionBar"

### ISSUE THREAD

**Issue by ashutosh-mulik** [oktavianto/ionalert#2]
FATAL EXCEPTION: main
    java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
        at androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java:843)
        at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:806)
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:693)
        at androidx.appcompat.app.AppCompatDialog.setContentView(AppCompatDialog.java:95)
        at androidx.appcompat.app.AlertController.installContent(AlertController.java:232)
        at androidx.appcompat.app.AlertDialog.onCreate(AlertDialog.java:279)
        at id.ionbit.ionalert.IonAlert.onCreate(IonAlert.java:99)
        at android.app.Dialog.dispatchOnCreate(Dialog.java:421)
        at android.app.Dialog.show(Dialog.java:315)

**Comment by rahat14** [comment]
change the application theme to any material theme
